/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-05-23 17:46:09 UTC)
 * on 2013-06-04 at 16:04:01 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.papiro.model;

/**
 * Model definition for AnuncioRs.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class AnuncioRs extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String extension;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String link;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String QRUrl;  
  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<PresentacionRs> presentaciones;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String thumbnail;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getExtension() {
    return extension;
  }

  /**
   * @param extension extension or {@code null} for none
   */
  public AnuncioRs setExtension(java.lang.String extension) {
    this.extension = extension;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public AnuncioRs setId(java.lang.String id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLink() {
    return link;
  }

  /**
   * @param link link or {@code null} for none
   */
  public AnuncioRs setLink(java.lang.String link) {
    this.link = link;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<PresentacionRs> getPresentaciones() {
    return presentaciones;
  }

  /**
   * @param presentaciones presentaciones or {@code null} for none
   */
  public AnuncioRs setPresentaciones(java.util.List<PresentacionRs> presentaciones) {
    this.presentaciones = presentaciones;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getThumbnail() {
    return thumbnail;
  }

  /**
   * @param thumbnail thumbnail or {@code null} for none
   */
  public AnuncioRs setThumbnail(java.lang.String thumbnail) {
    this.thumbnail = thumbnail;
    return this;
  }
  
  public String getQRUrl() {
      return QRUrl;
  }

  public AnuncioRs setQRUrl(String QRUrl) {
      this.QRUrl = QRUrl;
      return this;
  }

  @Override
  public AnuncioRs set(String fieldName, Object value) {
    return (AnuncioRs) super.set(fieldName, value);
  }

  @Override
  public AnuncioRs clone() {
    return (AnuncioRs) super.clone();
  }

}
