/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-05-23 17:46:09 UTC)
 * on 2013-06-04 at 16:04:01 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.papiro;

/**
 * Service definition for Papiro (v2).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link PapiroRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Papiro extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.15.0-rc of the  library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://papirodev.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "papiro/v2/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Papiro(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Papiro(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the Devices collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code Papiro papiro = new Papiro(...);}
   *   {@code Papiro.Devices.List request = papiro.devices().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public Devices devices() {
    return new Devices();
  }

  /**
   * The "devices" collection of methods.
   */
  public class Devices {

    /**
     * Create a request for the method "devices.config".
     *
     * This request holds the parameters needed by the the papiro server.  After setting any optional
     * parameters, call the {@link Config#execute()} method to invoke the remote operation.
     *
     * @param id
     * @param userKey
     * @return the request
     */
    public Config config(java.lang.String id, java.lang.String userKey) throws java.io.IOException {
      Config result = new Config(id, userKey);
      initialize(result);
      return result;
    }

    public class Config extends PapiroRequest<com.google.api.services.papiro.model.DispositivoConfigRs> {

      private static final String REST_PATH = "devices/config/{id}";

      /**
       * Create a request for the method "devices.config".
       *
       * This request holds the parameters needed by the the papiro server.  After setting any optional
       * parameters, call the {@link Config#execute()} method to invoke the remote operation. <p> {@link
       * Config#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
       * be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param id
       * @param userKey
       * @since 1.13
       */
      protected Config(java.lang.String id, java.lang.String userKey) {
        super(Papiro.this, "GET", REST_PATH, null, com.google.api.services.papiro.model.DispositivoConfigRs.class);
        this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
        this.userKey = com.google.api.client.util.Preconditions.checkNotNull(userKey, "Required parameter userKey must be specified.");
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public Config setAlt(java.lang.String alt) {
        return (Config) super.setAlt(alt);
      }

      @Override
      public Config setFields(java.lang.String fields) {
        return (Config) super.setFields(fields);
      }

      @Override
      public Config setKey(java.lang.String key) {
        return (Config) super.setKey(key);
      }

      @Override
      public Config setOauthToken(java.lang.String oauthToken) {
        return (Config) super.setOauthToken(oauthToken);
      }

      @Override
      public Config setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Config) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Config setQuotaUser(java.lang.String quotaUser) {
        return (Config) super.setQuotaUser(quotaUser);
      }

      @Override
      public Config setUserIp(java.lang.String userIp) {
        return (Config) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.String id;

      /**

       */
      public java.lang.String getId() {
        return id;
      }

      public Config setId(java.lang.String id) {
        this.id = id;
        return this;
      }

      @com.google.api.client.util.Key("user_key")
      private java.lang.String userKey;

      /**

       */
      public java.lang.String getUserKey() {
        return userKey;
      }

      public Config setUserKey(java.lang.String userKey) {
        this.userKey = userKey;
        return this;
      }

      @Override
      public Config set(String parameterName, Object value) {
        return (Config) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "devices.find".
     *
     * This request holds the parameters needed by the the papiro server.  After setting any optional
     * parameters, call the {@link Find#execute()} method to invoke the remote operation.
     *
     * @param id
     * @param userKey
     * @return the request
     */
    public Find find(java.lang.String id, java.lang.String userKey) throws java.io.IOException {
      Find result = new Find(id, userKey);
      initialize(result);
      return result;
    }

    public class Find extends PapiroRequest<com.google.api.services.papiro.model.DispositivoRs> {

      private static final String REST_PATH = "devices/{id}";

      /**
       * Create a request for the method "devices.find".
       *
       * This request holds the parameters needed by the the papiro server.  After setting any optional
       * parameters, call the {@link Find#execute()} method to invoke the remote operation. <p> {@link
       * Find#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must be
       * called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param id
       * @param userKey
       * @since 1.13
       */
      protected Find(java.lang.String id, java.lang.String userKey) {
        super(Papiro.this, "GET", REST_PATH, null, com.google.api.services.papiro.model.DispositivoRs.class);
        this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
        this.userKey = com.google.api.client.util.Preconditions.checkNotNull(userKey, "Required parameter userKey must be specified.");
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public Find setAlt(java.lang.String alt) {
        return (Find) super.setAlt(alt);
      }

      @Override
      public Find setFields(java.lang.String fields) {
        return (Find) super.setFields(fields);
      }

      @Override
      public Find setKey(java.lang.String key) {
        return (Find) super.setKey(key);
      }

      @Override
      public Find setOauthToken(java.lang.String oauthToken) {
        return (Find) super.setOauthToken(oauthToken);
      }

      @Override
      public Find setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Find) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Find setQuotaUser(java.lang.String quotaUser) {
        return (Find) super.setQuotaUser(quotaUser);
      }

      @Override
      public Find setUserIp(java.lang.String userIp) {
        return (Find) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.String id;

      /**

       */
      public java.lang.String getId() {
        return id;
      }

      public Find setId(java.lang.String id) {
        this.id = id;
        return this;
      }

      @com.google.api.client.util.Key("user_key")
      private java.lang.String userKey;

      /**

       */
      public java.lang.String getUserKey() {
        return userKey;
      }

      public Find setUserKey(java.lang.String userKey) {
        this.userKey = userKey;
        return this;
      }

      @Override
      public Find set(String parameterName, Object value) {
        return (Find) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "devices.list".
     *
     * This request holds the parameters needed by the the papiro server.  After setting any optional
     * parameters, call the {@link List#execute()} method to invoke the remote operation.
     *
     * @param firstResult
     * @param maxResult
     * @param userKey
     * @return the request
     */
    public List list(java.lang.Integer firstResult, java.lang.Integer maxResult, java.lang.String userKey) throws java.io.IOException {
      List result = new List(firstResult, maxResult, userKey);
      initialize(result);
      return result;
    }

    public class List extends PapiroRequest<com.google.api.services.papiro.model.DispositivoInfoRsCollection> {

      private static final String REST_PATH = "devices";

      /**
       * Create a request for the method "devices.list".
       *
       * This request holds the parameters needed by the the papiro server.  After setting any optional
       * parameters, call the {@link List#execute()} method to invoke the remote operation. <p> {@link
       * List#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must be
       * called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param firstResult
       * @param maxResult
       * @param userKey
       * @since 1.13
       */
      protected List(java.lang.Integer firstResult, java.lang.Integer maxResult, java.lang.String userKey) {
        super(Papiro.this, "GET", REST_PATH, null, com.google.api.services.papiro.model.DispositivoInfoRsCollection.class);
        this.firstResult = com.google.api.client.util.Preconditions.checkNotNull(firstResult, "Required parameter firstResult must be specified.");
        this.maxResult = com.google.api.client.util.Preconditions.checkNotNull(maxResult, "Required parameter maxResult must be specified.");
        this.userKey = com.google.api.client.util.Preconditions.checkNotNull(userKey, "Required parameter userKey must be specified.");
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public List setAlt(java.lang.String alt) {
        return (List) super.setAlt(alt);
      }

      @Override
      public List setFields(java.lang.String fields) {
        return (List) super.setFields(fields);
      }

      @Override
      public List setKey(java.lang.String key) {
        return (List) super.setKey(key);
      }

      @Override
      public List setOauthToken(java.lang.String oauthToken) {
        return (List) super.setOauthToken(oauthToken);
      }

      @Override
      public List setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (List) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public List setQuotaUser(java.lang.String quotaUser) {
        return (List) super.setQuotaUser(quotaUser);
      }

      @Override
      public List setUserIp(java.lang.String userIp) {
        return (List) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.Integer firstResult;

      /**

       */
      public java.lang.Integer getFirstResult() {
        return firstResult;
      }

      public List setFirstResult(java.lang.Integer firstResult) {
        this.firstResult = firstResult;
        return this;
      }

      @com.google.api.client.util.Key
      private java.lang.Integer maxResult;

      /**

       */
      public java.lang.Integer getMaxResult() {
        return maxResult;
      }

      public List setMaxResult(java.lang.Integer maxResult) {
        this.maxResult = maxResult;
        return this;
      }

      @com.google.api.client.util.Key("user_key")
      private java.lang.String userKey;

      /**

       */
      public java.lang.String getUserKey() {
        return userKey;
      }

      public List setUserKey(java.lang.String userKey) {
        this.userKey = userKey;
        return this;
      }

      @Override
      public List set(String parameterName, Object value) {
        return (List) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "devices.updateInfo".
     *
     * This request holds the parameters needed by the the papiro server.  After setting any optional
     * parameters, call the {@link UpdateInfo#execute()} method to invoke the remote operation.
     *
     * @param id
     * @param userKey
     * @return the request
     */
    public UpdateInfo updateInfo(java.lang.String id, java.lang.String userKey) throws java.io.IOException {
      UpdateInfo result = new UpdateInfo(id, userKey);
      initialize(result);
      return result;
    }

    public class UpdateInfo extends PapiroRequest<com.google.api.services.papiro.model.UpdateInfoRs> {

      private static final String REST_PATH = "devices/update-info/{id}";

      /**
       * Create a request for the method "devices.updateInfo".
       *
       * This request holds the parameters needed by the the papiro server.  After setting any optional
       * parameters, call the {@link UpdateInfo#execute()} method to invoke the remote operation. <p>
       * {@link
       * UpdateInfo#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param id
       * @param userKey
       * @since 1.13
       */
      protected UpdateInfo(java.lang.String id, java.lang.String userKey) {
        super(Papiro.this, "GET", REST_PATH, null, com.google.api.services.papiro.model.UpdateInfoRs.class);
        this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
        this.userKey = com.google.api.client.util.Preconditions.checkNotNull(userKey, "Required parameter userKey must be specified.");
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public UpdateInfo setAlt(java.lang.String alt) {
        return (UpdateInfo) super.setAlt(alt);
      }

      @Override
      public UpdateInfo setFields(java.lang.String fields) {
        return (UpdateInfo) super.setFields(fields);
      }

      @Override
      public UpdateInfo setKey(java.lang.String key) {
        return (UpdateInfo) super.setKey(key);
      }

      @Override
      public UpdateInfo setOauthToken(java.lang.String oauthToken) {
        return (UpdateInfo) super.setOauthToken(oauthToken);
      }

      @Override
      public UpdateInfo setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (UpdateInfo) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public UpdateInfo setQuotaUser(java.lang.String quotaUser) {
        return (UpdateInfo) super.setQuotaUser(quotaUser);
      }

      @Override
      public UpdateInfo setUserIp(java.lang.String userIp) {
        return (UpdateInfo) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.String id;

      /**

       */
      public java.lang.String getId() {
        return id;
      }

      public UpdateInfo setId(java.lang.String id) {
        this.id = id;
        return this;
      }

      @com.google.api.client.util.Key("user_key")
      private java.lang.String userKey;

      /**

       */
      public java.lang.String getUserKey() {
        return userKey;
      }

      public UpdateInfo setUserKey(java.lang.String userKey) {
        this.userKey = userKey;
        return this;
      }

      @Override
      public UpdateInfo set(String parameterName, Object value) {
        return (UpdateInfo) super.set(parameterName, value);
      }
    }

  }

  /**
   * Builder for {@link Papiro}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Papiro}. */
    @Override
    public Papiro build() {
      return new Papiro(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link PapiroRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setPapiroRequestInitializer(
        PapiroRequestInitializer papiroRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(papiroRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
